# Ingress for v1.0.0
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-api-ingress-v1
  namespace: product-v1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: product.local
      http:
        paths:
          - path: /v1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product-service
                port:
                  number: 80
---
# Ingress for v1.1.0
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-api-ingress-v1-1
  namespace: product-v1-1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: product.local
      http:
        paths:
          - path: /v1-1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product-service
                port:
                  number: 80
---
# Ingress for v2.0.0
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-api-ingress-v2
  namespace: product-v2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: product.local
      http:
        paths:
          - path: /v2(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product-service
                port:
                  number: 80
