apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: product-v1
spec:
  selector:
    app: product-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9191
  type: NodePort
